emp=read.csv("data/emp.csv")
emp %>% filter(job == "MANAGER")
emp %>% select(empno,ename,sal)
emp %>% select(-empno)
emp %>% select(ename,sal)
emp %>% group_by(job)
emp %>% filter(sal>=1000 & sal<=3000) %>% select(ename,sal,deptno)
emp %>% filter(!job=="ANALYST") %>% select(ename,job,sal)
emp %>% filter(!job=="SALESMAN",!job=="ANALYST") %>% select(ename,job)
emp %>% group_by(job) %>% summarise(length(job))
emp %>% arrange(sal)
emp %>% arrange(desc(sal)) %>% head(1)
empnew = emp %>% mutate(salary = sal) %>% mutate(commrate = comm) %>% select(-sal,-comm)
emp %>% group_by(deptno) %>% summarise(length(deptno)) %>% arrange() %>% tail(1) %>% select(deptno)
emp %>% mutate(enamelength = nchar(as.character(ename))) %>% arrange(enamelength)
emp %>% filter(!comm == "NA") %>% nrow()